<?php $this->headTitle('Table'); ?>

<div class="jumbotron">


    <?php if(isset($this->table)):?>
        <p><?php
            for($i=0; $i<sizeof($this->table);$i++) {?>
                <p>
                <?php echo 'Id: ' . $this->table[$i]['id'] . ' First name: '. $this->table[$i]['firstname']. ' Last name: '. $this->table[$i]['lastname'] . ' Email: ' . $this->table[$i]['email']; ?>
                </p>
            <?}
            ?>
        </p>
    <?php endif;?>

</div>